# Generated by Django 5.0.6 on 2024-07-05 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0002_alter_consultation_options_and_more"),
        ("patients", "0002_alter_patient_options_alter_patient_patient_bday_and_more"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "수납", "verbose_name_plural": "수납"},
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.IntegerField(verbose_name="금액"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="consultation_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="consultations.consultation",
                verbose_name="진료번호",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="patient_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patient",
                verbose_name="환자",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="결제 날짜"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(max_length=50, verbose_name="결제방법"),
        ),
    ]
