# Generated by Django 5.0.6 on 2024-07-05 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0003_alter_doctor_options_alter_doctor_departments_id_and_more"),
        ("patients", "0002_alter_patient_options_alter_patient_patient_bday_and_more"),
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"verbose_name": "예약", "verbose_name_plural": "예약들"},
        ),
        migrations.AlterField(
            model_name="reservation",
            name="doctor_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors.doctor",
                verbose_name="의사",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="patient_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patient",
                verbose_name="환자이름",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_date",
            field=models.DateTimeField(verbose_name="예약 날짜"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_status",
            field=models.IntegerField(
                choices=[(0, "예약됨"), (1, "대기중"), (2, "완료"), (3, "불참")],
                verbose_name="예약 상태",
            ),
        ),
    ]
