# Generated by Django 5.0.6 on 2024-07-04 05:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "병원 관계자"},
        ),
    ]
