# Generated by Django 5.0.6 on 2024-07-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "병원 관계자", "verbose_name_plural": "병원 관계자들"},
        ),
        migrations.AlterField(
            model_name="user",
            name="is_approved",
            field=models.IntegerField(default=0, verbose_name="승인여부"),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(max_length=200, unique=True, verbose_name="아이디"),
        ),
    ]
