# Generated by Django 5.0.6 on 2024-07-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescriptions", "0002_alter_prescription_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="prescription_image",
            field=models.ImageField(
                upload_to="images/prescriptions", verbose_name="처방전"
            ),
        ),
    ]
