# Generated by Django 5.0.6 on 2024-07-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FloorMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floor", models.IntegerField()),
                ("floor_image", models.ImageField(upload_to="")),
            ],
            options={
                "verbose_name": "층지도",
                "db_table": "floor_map",
            },
        ),
    ]
