# Generated by Django 5.0.6 on 2024-07-04 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Departments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departments_name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "진료부서",
                "db_table": "departments",
            },
        ),
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disease_name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "질병",
                "db_table": "disease",
            },
        ),
        migrations.CreateModel(
            name="DepartmentLocations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departments_image", models.ImageField(upload_to="")),
                (
                    "departments_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departments.departments",
                    ),
                ),
            ],
            options={
                "verbose_name": "과별 지도",
                "db_table": "department_locations",
            },
        ),
        migrations.AddField(
            model_name="departments",
            name="diseases",
            field=models.ManyToManyField(to="departments.disease"),
        ),
    ]
