# Generated by Django 5.0.6 on 2024-07-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0002_departments_disease_departmentlocations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departments",
            name="diseases",
            field=models.ManyToManyField(blank=True, to="departments.disease"),
        ),
    ]
