# Generated by Django 5.0.6 on 2024-07-05 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0003_alter_departments_diseases"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="departmentlocations",
            options={"verbose_name": "과별 지도", "verbose_name_plural": "과별 지도들"},
        ),
        migrations.AlterModelOptions(
            name="departments",
            options={"verbose_name": "진료부서", "verbose_name_plural": "진료부서들"},
        ),
        migrations.AlterModelOptions(
            name="disease",
            options={"verbose_name": "질병", "verbose_name_plural": "질병들"},
        ),
        migrations.AlterModelOptions(
            name="floormap",
            options={"verbose_name": "층지도", "verbose_name_plural": "층지도"},
        ),
        migrations.AlterField(
            model_name="departmentlocations",
            name="departments_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="departments.departments",
                verbose_name="진료부서",
            ),
        ),
        migrations.AlterField(
            model_name="departmentlocations",
            name="departments_image",
            field=models.ImageField(upload_to="images/", verbose_name="진료부서 이미지"),
        ),
        migrations.AlterField(
            model_name="departments",
            name="departments_name",
            field=models.CharField(max_length=100, verbose_name="진료부서명"),
        ),
        migrations.AlterField(
            model_name="departments",
            name="diseases",
            field=models.ManyToManyField(
                blank=True, to="departments.disease", verbose_name="질병"
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="disease_name",
            field=models.CharField(max_length=200, verbose_name="질병명"),
        ),
        migrations.AlterField(
            model_name="floormap",
            name="floor",
            field=models.IntegerField(verbose_name="층"),
        ),
        migrations.AlterField(
            model_name="floormap",
            name="floor_image",
            field=models.ImageField(upload_to="images/", verbose_name="층 이미지"),
        ),
    ]
