# Generated by Django 5.0.6 on 2024-07-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0004_alter_departmentlocations_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departmentlocations",
            name="departments_image",
            field=models.ImageField(
                upload_to="images/department/", verbose_name="진료부서 이미지"
            ),
        ),
        migrations.AlterField(
            model_name="floormap",
            name="floor_image",
            field=models.ImageField(upload_to="images/floormap/", verbose_name="층 이미지"),
        ),
    ]
