# Generated by Django 5.0.6 on 2024-07-16 10:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0005_alter_departmentlocations_departments_image_and_more"),
        ("doctors", "0004_remove_doctor_diseases"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departments",
            name="diseases",
        ),
        migrations.DeleteModel(
            name="Disease",
        ),
    ]
