# Generated by Django 5.0.6 on 2024-07-04 05:04


from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=200)),
                ("patient_birth", models.DateField()),
            ],
            options={
                "verbose_name": "환자",
                "db_table": "patient",
            },
        ),
    ]
