# Generated by Django 5.0.6 on 2024-07-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="patient_bday",
            field=models.CharField(default="000000", max_length=6),
        ),
    ]
