# Generated by Django 5.0.6 on 2024-07-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_alter_patient_options_alter_patient_patient_bday_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="patient_bday_formatted",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="생년월일(YY년 M월 D일)"
            ),
        ),
    ]
