# Generated by Django 5.0.6 on 2024-07-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_patient_patient_bday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="patient_bday",
            field=models.CharField(blank=True, default="000000", max_length=6),
        ),
    ]
