# Generated by Django 5.0.6 on 2024-07-04 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("departments", "0002_departments_disease_departmentlocations_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor_name", models.CharField(max_length=100)),
                ("information", models.TextField()),
                (
                    "departments_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departments.departments",
                    ),
                ),
                ("diseases", models.ManyToManyField(to="departments.disease")),
            ],
            options={
                "verbose_name": "의사",
                "db_table": "doctor",
            },
        ),
    ]
