# Generated by Django 5.0.6 on 2024-07-05 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0004_alter_departmentlocations_options_and_more"),
        ("doctors", "0002_alter_doctor_diseases"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctor",
            options={"verbose_name": "의사", "verbose_name_plural": "의사들"},
        ),
        migrations.AlterField(
            model_name="doctor",
            name="departments_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="departments.departments",
                verbose_name="진료부서명",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="diseases",
            field=models.ManyToManyField(
                blank=True, to="departments.disease", verbose_name="질병"
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="doctor_name",
            field=models.CharField(max_length=100, verbose_name="의사이름"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="information",
            field=models.TextField(verbose_name="의사설명"),
        ),
    ]
