# Generated by Django 5.0.6 on 2024-07-16 10:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0003_alter_doctor_options_alter_doctor_departments_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="diseases",
        ),
    ]
